# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper;/Users/ac/Dev/aibox/app/open-orienteering-map/mapper")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMMAND_HDIUTIL "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/packaging/macos/hdiutil.sh")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Mapper built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "DragNDrop")
set(CPACK_GENERATOR_DEFAULT "DragNDrop")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper;Mapper;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/cmake;/opt/homebrew/lib/cmake/Qt6;/opt/homebrew/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/opt/homebrew/lib/cmake/Qt6/3rdparty/kwin;/opt/homebrew/lib/cmake/Qt6;/opt/homebrew/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/opt/homebrew/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "OpenOrienteering Mapper 0.9.7")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "OpenOrienteering Mapper 0.9.7")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Map drawing program from OpenOrienteering")
set(CPACK_PACKAGE_EXECUTABLES "Mapper;OpenOrienteering Mapper 0.9.7")
set(CPACK_PACKAGE_FILE_NAME "OpenOrienteering-Mapper-0.9.7-macOS")
set(CPACK_PACKAGE_ICON "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/images/mapper-icon/Mapper.icns")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "OpenOrienteering Mapper 0.9.7")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OpenOrienteering Mapper 0.9.7")
set(CPACK_PACKAGE_NAME "OpenOrienteering Mapper")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "OpenOrienteering")
set(CPACK_PACKAGE_VERSION "0.9.7")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "9")
set(CPACK_PACKAGE_VERSION_PATCH "7")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/COPYING")
set(CPACK_RESOURCE_FILE_README "/opt/homebrew/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/homebrew/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "OFF;TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_GENERATOR "OFF;TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper;/[.]git/;/3rd-party/clipper/download/;/3rd-party/proj/download/;/3rd-party/qt5/download/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "openorienteering-mapper_0.9.7-src")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "TRUE")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/ac/Dev/aibox/app/open-orienteering-map/mapper/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
